<?xml version="1.0" encoding="utf-8"?><Database Name="TSQLV4" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VKQTCJN;Initial Catalog=TSQLV4;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TSQLV4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="HR.Employees" Member="Employees">
    <Type Name="Employee" Id="ID1">
      <Column Name="empid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="titleofcourtesy" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hiredate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="postalcode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="mgrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Employee" Member="Employees" ThisKey="empid" OtherKey="mgrid" Type="Employee" />
      <Association Name="Employee_Employee" Member="Employee1" ThisKey="mgrid" OtherKey="empid" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.getEmployees" Method="getEmployees">
    <ElementType IdRef="ID1" />
  </Function>
</Database>